notifications:
  email:
    on_success: never
    on_failure: always

language: php

services:
  - mysql
  - postgresql
  - docker

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - "7.3"
  - "7.5"
  - "8.0"

env:
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat