# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.0','7.3', '8.0']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up PHP.
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          phpenv config-rm xdebug.ini
          cd ../..
          composer selfupdate
          composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
          export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
