# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ move-github-actions ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.0']
        db: ['pgsql', 'mysqli']
        moodle_branch: ['MOODLE_38_STABLE', 'MOODLE_39_STABLE']
        db_user: ['root']
        db_pass: ['root']
    env:
      DB: ${{ matrix.db }}
      MOODLE_BRANCH: ${{ matrix.moodle_branch }}

    services:
      postgres:
        image: postgres

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Setup Mysqli
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql user: ${{ matrix.db_user }}
          mysql password: ${{ matrix.db_pass }}


      - name: Run mysqli
        run: |
          sudo service mysql start

      - name: Setup PgSql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql user: ${{ matrix.db_user }}
          postgresql password: ${{ matrix.db_pass }}

      # Set up PHP.
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Set up moodle plugin ci
        run: |
          pwd
          cd ../..
          pwd
          composer selfupdate
          composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
          echo "$(cd ci/bin; pwd)" >> $GITHUB_PATH
          echo "$(cd ci/vendor/bin; pwd)" >> $GITHUB_PATH
          echo $PATH
          cd ci/bin
          ls -la


      - name: Install Moodle CI
        run: |
          echo $PATH
          moodle-plugin-ci install --db-pass ${{ matrix.db_pass }} --db-user ${{ matrix.db_user }}

      - name: Run tests
        run: |
          moodle-plugin-ci phplint
          moodle-plugin-ci phpcpd
          moodle-plugin-ci phpmd
          moodle-plugin-ci codechecker
          moodle-plugin-ci csslint
          moodle-plugin-ci shifter
          moodle-plugin-ci jshint
          moodle-plugin-ci validate
          moodle-plugin-ci phpunit
          moodle-plugin-ci behat

      - name: Debugging
      if: failure()
        run: |
          sudo service mysql start
          systemctl status mysql.service
          journalctl -xe

