# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ move-github-actions ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.0']
        db: ['mysqli']
        moodle_branch: ['MOODLE_38_STABLE', 'MOODLE_39_STABLE']
    env:
      DB: ${{ matrix.db }}
      MOODLE_BRANCH: ${{ matrix.moodle_branch }}

    services:
      postgres:
        image: postgres

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run mysqli
        run: |
          sudo service mysql restart
          sudo service postgresql restart

      # Set up PHP.
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Set up moodle plugin ci
        run: |
          cd ../..
          composer selfupdate
          composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
          echo "$(cd ci/bin; pwd)" >> $GITHUB_PATH
          echo "$(cd ci/vendor/bin; pwd)" >> $GITHUB_PATH


      - name: Install Moodle CI
        run: |
          echo $PATH
          moodle-plugin-ci install

      - name: Run tests
        run: |
          moodle-plugin-ci phplint
          moodle-plugin-ci phpcpd
          moodle-plugin-ci phpmd
          moodle-plugin-ci codechecker
          moodle-plugin-ci csslint
          moodle-plugin-ci shifter
          moodle-plugin-ci jshint
          moodle-plugin-ci validate
          moodle-plugin-ci phpunit
          moodle-plugin-ci behat

      - name: Debugging
        if: ${{ failure() }}
        run: |
          systemctl status mysql.service
          journalctl -xe

